### ISSUE TITLE
No SSR

### ISSUE THREAD

**Issue by Richard1984** [ITISEnricoFermi/silver-computing-raspberry#2]
Elimina tutto quello che è server side rendering (quindi HBS) che tanto è una single page application.

**Comment by n4y0n** [comment]
Ho lasciato un "Hello" quando visiti l'index 'cause why not?

**Comment by Richard1984** [comment]
Perché come ho detto è una single page application, quindi il server non deve fare nulla. Così risparmi pure cone le dipendenze.
